### ISSUE TITLE
Write test launcher script

### ISSUE THREAD

**Issue by jgaye** [jgaye/HanjiesSolver#6]
Depends on #3 , #4

**Comment by vpucci** [comment]
I will investigate on the existing Python-specific test framework called "unittest" and try to evaluate whether it's worth using it or not

**Comment by vpucci** [comment]
First step is already implemented.
Next implementation step consist of implementing a test launcher in order to run a single test at once specified by its name.

**Comment by jgaye** [comment]
Done
